# Generated by Django 3.0.8 on 2023-03-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
